<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GNusGuRService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.GNusGuR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GNusGuR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'configRepository' => ['privates', 'Plugin\\ProductReview42\\Repository\\ProductReviewConfigRepository', 'getProductReviewConfigRepositoryService', true],
        ], [
            'configRepository' => 'Plugin\\ProductReview42\\Repository\\ProductReviewConfigRepository',
        ]);
    }
}
