<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TcwBNPwService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.tcwBNPw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tcwBNPw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'RecommendProduct' => ['privates', '.errored..service_locator.tcwBNPw.Plugin\\Recommend42\\Entity\\RecommendProduct', NULL, 'Cannot autowire service ".service_locator.tcwBNPw": it references class "Plugin\\Recommend42\\Entity\\RecommendProduct" but no such service exists.'],
        ], [
            'RecommendProduct' => 'Plugin\\Recommend42\\Entity\\RecommendProduct',
        ]);
    }
}
