<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddClientDefaultScopesListenerService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'League\Bundle\OAuth2ServerBundle\EventListener\AddClientDefaultScopesListener' shared service.
     *
     * @return \League\Bundle\OAuth2ServerBundle\EventListener\AddClientDefaultScopesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'league'.\DIRECTORY_SEPARATOR.'oauth2-server-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'AddClientDefaultScopesListener.php';

        return $container->privates['League\\Bundle\\OAuth2ServerBundle\\EventListener\\AddClientDefaultScopesListener'] = new \League\Bundle\OAuth2ServerBundle\EventListener\AddClientDefaultScopesListener($container->parameters['league.oauth2_server.scopes.default']);
    }
}
