<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityListenerService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'Plugin\Api42\Doctrine\EventSubscriber\EntityListener' shared autowired service.
     *
     * @return \Plugin\Api42\Doctrine\EventSubscriber\EntityListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'event-manager'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api42'.\DIRECTORY_SEPARATOR.'Doctrine'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'EntityListener.php';

        return $container->privates['Plugin\\Api42\\Doctrine\\EventSubscriber\\EntityListener'] = new \Plugin\Api42\Doctrine\EventSubscriber\EntityListener(($container->privates['Plugin\\Api42\\Service\\WebHookEvents'] ?? $container->getWebHookEventsService()));
    }
}
