<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductReviewEventService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'Plugin\ProductReview42\ProductReviewEvent' shared autowired service.
     *
     * @return \Plugin\ProductReview42\ProductReviewEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'ProductReview42'.\DIRECTORY_SEPARATOR.'ProductReviewEvent.php';

        return $container->privates['Plugin\\ProductReview42\\ProductReviewEvent'] = new \Plugin\ProductReview42\ProductReviewEvent(($container->privates['Plugin\\ProductReview42\\Repository\\ProductReviewConfigRepository'] ?? $container->load('getProductReviewConfigRepositoryService')), ($container->privates['Eccube\\Repository\\Master\\ProductStatusRepository'] ?? $container->load('getProductStatusRepositoryService')), ($container->privates['Plugin\\ProductReview42\\Repository\\ProductReviewRepository'] ?? $container->load('getProductReviewRepositoryService')));
    }
}
