<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductReviewService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.O_p9pDn.Plugin\ProductReview42\Entity\ProductReview' shared service.
     *
     * @return \Plugin\ProductReview42\Entity\ProductReview
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.O_p9pDn": it references class "Plugin\\ProductReview42\\Entity\\ProductReview" but no such service exists.');
    }
}
