<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendProductService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.tcwBNPw.Plugin\Recommend42\Entity\RecommendProduct' shared service.
     *
     * @return \Plugin\Recommend42\Entity\RecommendProduct
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tcwBNPw": it references class "Plugin\\Recommend42\\Entity\\RecommendProduct" but no such service exists.');
    }
}
