<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendControllerService extends Eccube_KernelProdContainer
{
    /*
     * Gets the public 'Plugin\Recommend42\Controller\RecommendController' shared autowired service.
     *
     * @return \Plugin\Recommend42\Controller\RecommendController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Recommend42'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'RecommendController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Recommend42'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecommendService.php';

        $a = ($container->privates['Plugin\\Recommend42\\Repository\\RecommendProductRepository'] ?? $container->load('getRecommendProductRepositoryService'));

        $container->services['Plugin\\Recommend42\\Controller\\RecommendController'] = $instance = new \Plugin\Recommend42\Controller\RecommendController($a, new \Plugin\Recommend42\Service\RecommendService($a));

        $instance->setEccubeConfig(($container->services['Eccube\\Common\\EccubeConfig'] ?? ($container->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($container))));
        $instance->setEntityManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setSession(($container->services['.container.private.session'] ?? $container->get_Container_Private_SessionService()));
        $instance->setFormFactory(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')));
        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $instance->setContainer(($container->privates['.service_locator.s_TJPfT'] ?? $container->load('get_ServiceLocator_STJPfTService'))->withContext('Plugin\\Recommend42\\Controller\\RecommendController', $container));

        return $instance;
    }
}
