<?php

namespace ContainerP8FTNAX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebHookService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.gVkmJLw.Plugin\Api42\Entity\WebHook' shared service.
     *
     * @return \Plugin\Api42\Entity\WebHook
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gVkmJLw": it references class "Plugin\\Api42\\Entity\\WebHook" but no such service exists.');
    }
}
